sudo: false

language: node_js
node_js:
  - 4

env:
  - PKG_DIR=packages/react-portal

cache:
  directories:
    - node_modules

after_install:
  - "export PATH=$PWD/node_modules/.bin:$PATH"

script: cd $PKG_DIR && npm install && npm test
