sudo: false

branches:
  only:
    - master

before_install:
  - "npm install"
  - "export PATH=$PWD/node_modules/.bin:$PATH"

language: node_js
node_js:
  - 4

env:
  - PKG_DIR=packages/react-portal

cache:
  directories:
    - node_modules
    - $PKG_DIR/node_modules

script: cd $PKG_DIR && npm install && npm test
